// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://twtlclmuiigwgvjtxxrc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR3dGxjbG11aWlnd2d2anR4eHJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMjI5MjAsImV4cCI6MjA2OTY5ODkyMH0.chpAU7HtSk5KTwCFBgnHRqZ_o7FEf2valqjVIiNKMt4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});